const workoutData = [
  {
    muscleGroup: 'chest',
    description: 'chest workout for pectorial muscle',
    exercises: [
      { name: 'Flat Bench press', description: '' },
      { name: 'Incline bench press', description: '' },
      { name: 'Decline bench press', description: '' },
      { name: 'Flat Dumbell press', description: '' },
      { name: 'Incline Dumbell press', description: '' },
      { name: 'Decline Dumbell press', description: '' },
      { name: 'Incline Dumbell bench flies', description: '' },
      { name: 'Decline Dumbell bench flies', description: '' },
      { name: 'Flat bench Dumbell flies', description: '' },
      { name: 'Cable flies', description: '' },
    ],
    reps: 10,
    sets: 10,
  },
  {
    muscleGroup: 'back',
    description: 'back workout for lats, traps and whole back',
    exercises: [
      { name: ' Over-hand barbell rows', description: '' },
      { name: 'Bent-over dumbell rows', description: '' },
      { name: 'One arm Dumbell rows', description: '' },
      { name: 'Under-hand barbell rows', description: '' },
      { name: 'T-bar rows', description: '' },
      { name: 'Shrugs', description: '' },
      { name: 'Pull-ups', description: '' },
      { name: 'Sitted rows', description: '' },
      { name: 'Wide-grip Lats pull-downs', description: '' },
      { name: 'Close-grip Lats pull-downs', description: '' },
      { name: 'Dumbell pull-overs', description: '' },
      { name: 'Standing pull-overs', description: '' },
      { name: 'Deadlift', description: '' },

    ],
    reps: 10,
    sets: 10,
  },
  {
    muscleGroup: 'legs',
    description: 'legs workouts for the quads, hamstings and calves',
    exercises: [
      { name: 'Squats', description: '' },
      { name: 'Front squats', description: '' },
      { name: 'Hack squats', description: '' },
      { name: 'Barbell launges', description: '' },
      { name: 'Dumbell launges', description: '' },
      { name: 'Stiff-leg deadlift', description: '' },
      { name: 'Hamstring curls', description: '' },
      { name: 'Calf raises', description: '' },
      { name: 'Box jumps', description: '' },
      { name: 'Inner adductor workout', description: '' },
      { name: 'Seated calves raises', description: '' },
    ],
    reps: 10,
    sets: 10,
  },
  {
    muscleGroup: 'shoulders',
    description: 'shoulder workouts for the deltiods',
    exercises: [
      { name: 'Dumbell shoulder press', description: '' },
      { name: 'Arnold press', description: '' },
      { name: 'Barbell shoulder press', description: '' },
      { name: 'Barbell high pull', description: '' },
      { name: 'Barbell front reaises', description: '' },
      { name: 'Dumbell front raises', description: '' },
      { name: 'Side raises', description: '' },
      { name: 'Rear delt raises', description: '' },
    ],
    reps: 10,
    sets: 10,
  },
  {
    muscleGroup: 'bicep',
    description: 'bicep workout for the arms',
    exercises: [
      { name: 'Barbell curls', description: '' },
      { name: 'Dumbell curls', description: '' },
      { name: 'Hammer curls', description: '' },
      { name: 'Seated dumbell curls', description: '' },
      { name: 'Inside grip EZ bar curls', description: '' },
      { name: 'Wide grip EZ bar curls', description: '' },
      { name: 'Close grip pull ups', description: '' },
      { name: 'Dumbell Preacher curls', description: '' },
      { name: 'Barbell preacher curls', description: '' },
    ],
    reps: 10,
    sets: 10,
  },
  {
    muscleGroup: 'tricep',
    description: 'tricep workout for the arms',
    exercises: [
      { name: 'Barbell reverse grip tricep extension', description: ''},
      { name: 'Tricep dips', description: ''},
      { name: 'Tricep push-downs', description: ''},
      { name: 'Close grip bench press', description: ''},
      { name: 'Reverse dips', description: ''},
      { name: 'Standing dumbell tricep extension', description: ''},
      { name: 'Tricep kickbacks', description: ''},
    ],
    reps: 10,
    sets: 10,
  },
  {
    muscleGroup: 'abs',
    description: 'abs workout for the abdominal muscle',
    exercises: [
      { name: 'Ab wheel rollout', description: ''},
      { name: 'Alternating disgonal crunch', description: ''},
      { name: 'Sit-ups', description: ''},
      { name: 'Bicycle crunch', description: ''},
      { name: 'Crunch with twist', description: ''},
      { name: 'Decline sit-ups', description: ''},
      { name: 'Elbow plank', description: ''},
      { name: 'Floor crunch', description: ''},
      { name: 'Exercise ball reverse crunch', description: ''},
    ],
    reps: 10,
    sets: 10,
  },
  {
    muscleGroup: 'cardio',
    description: 'cardio exercises for the cardiovascular system',
    exercises: [
      { name:'Elliptical trainer', description: ''},
      { name:'Exercise bike', description: ''},
      { name:'Exercise bike training', description: ''},
      { name:'Rowing machine', description: ''},
      { name:'Stepper', description: ''},
      { name:'Treadmill', description: ''},
      { name:'Boxing bag', description: ''},
    ],
    reps: 10,
    sets: 10,
  },
  {
    muscleGroup: 'stretching',
    description: 'stretch exercises for the joins and mobility',
    exercises: [
      { name: 'Against wall chest stretch', description: ''},
      { name: 'Butterfly stretch', description: ''},
      { name: 'Cat-cow pose', description: ''},
      { name: "Child's pose stretch", description: ''},
      { name: 'Deltoids stretch', description: ''},
      { name: 'Low lunge with one are raise', description: ''},
      { name: 'lyiing gluteal stretch', description: ''},
      { name: 'Overhead triceps stretch', description: ''},
      { name: 'Quadriceps stretch', description: ''},
    ],
    reps: 10,
    sets: 10,
  },
];

export default workoutData;
