const workoutData = [
  {
    muscleGroup: 'chest',
    description: 'chest workout for pectorial muscle',
    exercises: [
      'Flat Bench press',
      'Incline bench press',
      'Decline bench press',
      'Flat Dumbell press',
      'Incline Dumbell press',
      'Decline Dumbell press',
      'Incline Dumbell bench flies',
      'Decline Dumbell bench flies',
      'Flat bench Dumbell flies',
      'Cable flies',
    ],
    reps: 10,
    sets: 10,
  },
  {
    muscleGroup: 'back',
    description: 'back workout for lats, traps and whole back',
    exercises: [
      'One arm Dumbell rows',
      'Bent-over dumbell rows',
      ' Over-hand barbell rows',
      'Under-hand barbell rows',
      'T-bar rows',
      'Shrugs',
      'Pull-ups',
      'Sitted rows',
      'Wide-grip Lats pull-downs',
      'Close-grip Lats pull-downs',
      'Dumbell pull-overs',
      'Standing pull-overs',
      'Deadlift',

    ],
    reps: 10,
    sets: 10,
  },
  {
    muscleGroup: 'legs',
    description: 'legs workouts for the quads, hamstings and calves',
    exercises: [
      'Squats',
      'Front squats',
      'Hack squats',
      'Barbell launges',
      'Dumbell launges',
      'Stiff-leg deadlift',
      'Hamstring curls',
      'Calf raises',
      'Box jumps',
      'Inner adductor workout',
      'Seated calves raises',
    ],
    reps: 10,
    sets: 10,
  },
  {
    muscleGroup: 'shoulders',
    description: 'shoulder workouts for the deltiods',
    exercises: [
      'Dumbell shoulder press',
      'Arnold press',
      'Barbell shoulder press',
      'Barbell high pull',
      'Barbell front reaises',
      'Dumbell front raises',
      'Side raises',
      'Rear delt raises',
    ],
    reps: 10,
    sets: 10,
  },
  {
    muscleGroup: 'bicep',
    description: 'bicep workout for the arms',
    exercises: [
      'Barbell curls',
      'Dumbell curls',
      'Hammer curls',
      'Seated dumbell curls',
      'Inside grip EZ bar curls',
      'Wide grip EZ bar curls',
      'Close grip pull ups',
      'Dumbell Preacher curls',
      'Barbell preacher curls',
    ],
    reps: 10,
    sets: 10,
  },
  {
    muscleGroup: 'tricep',
    description: 'tricep workout for the arms',
    exercises: [
      'Barbell reverse grip tricep extension',
      'Tricep dips',
      'Tricep push-downs',
      'Close grip bench press',
      'Reverse dips',
      'Standing dumbell tricep extension',
      'Tricep kickbacks',
    ],
    reps: 10,
    sets: 10,
  },
  {
    muscleGroup: 'abs',
    description: 'abs workout for the abdominal muscle',
    exercises: [
      'Ab wheel rollout',
      'Alternating disgonal crunch',
      'Sit-ups',
      'Bicycle crunch',
      'Crunch with twist',
      'Decline sit-ups',
      'Elbow plank',
      'Floor crunch',
      'Exercise ball reverse crunch',
    ],
    reps: 10,
    sets: 10,
  },
  {
    muscleGroup: 'cardio',
    description: 'cardio exercises for the cardiovascular system',
    exercises: [
      'Elliptical trainer',
      'Exercise bike',
      'Exercise bike training',
      'Rowing machine',
      'Stepper',
      'Treadmill',
      'Boxing bag',
    ],
    reps: 10,
    sets: 10,
  },
  {
    muscleGroup: 'stretching',
    description: 'stretch exercises for the joins and mobility',
    exercises: [
      'Against wall chest stretch',
      'Butterfly stretch',
      'Cat-cow pose',
      "Child's pose stretch",
      'Deltoids stretch',
      'Low lunge with one are raise',
      'lyiing gluteal stretch',
      'Overhead triceps stretch',
      'Quadriceps stretch',
    ],
    reps: 10,
    sets: 10,
  },
];

export default workoutData;
